version: "2.1"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: restdb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345 --execute \"SHOW DATABASES;\""
  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/code
    image:
      "wowah/restapitest" 
    depends_on:
      mysql:
        condition: service_healthy